"""Constants for Home Energy Orchestrator."""

from __future__ import annotations

DOMAIN = "home_energy_orchestrator"
PLATFORMS = ["sensor", "binary_sensor", "number", "button", "switch", "select"]

CONF_BATTERY_SOC = "battery_soc_entity"
CONF_BATTERY_POWER = "battery_power_entity"
# Preferred pilot-faithful mapping. When both magnitude sensors are supplied,
# HEO calculates charge minus discharge and ignores the signed fallback above.
CONF_BATTERY_CHARGE_POWER = "battery_charge_power_entity"
CONF_BATTERY_DISCHARGE_POWER = "battery_discharge_power_entity"
CONF_BATTERY_CHARGE_POSITIVE = "battery_charge_positive"
CONF_BATTERY_POWER_DIRECTION = "battery_power_positive_direction"
CONF_BATTERY_CAPACITY_ENTITY = "battery_capacity_entity"
CONF_BATTERY_CAPACITY = "battery_capacity_kwh"
CONF_BATTERY_FLOOR = "battery_floor_percent"
CONF_GRID_POWER = "grid_power_entity"
CONF_DAILY_IMPORT_ENTITY = "daily_import_entity"
CONF_DAILY_FREE_ALLOWANCE_KWH = "daily_free_allowance_kwh"
CONF_PEAK_WINDOW_START = "peak_window_start"
CONF_PEAK_WINDOW_END = "peak_window_end"
CONF_PEAK_RATE = "peak_rate_per_kwh"
CONF_OFFPEAK_RATE = "offpeak_rate_per_kwh"
CONF_OFFPEAK_BALANCE_RATE = "offpeak_balance_rate_per_kwh"
CONF_SHOULDER_RATE = "shoulder_rate_per_kwh"
CONF_EXPORT_RATE = "export_rate_per_kwh"
CONF_SUPER_EXPORT_RATE = "super_export_rate_per_kwh"
CONF_DAILY_CHARGE = "daily_charge"
CONF_GRID_IMPORT_POSITIVE = "grid_import_positive"
CONF_GRID_POWER_DIRECTION = "grid_power_positive_direction"
CONF_SITE_PHASE_COUNT = "site_phase_count"
CONF_SERVICE_IMPORT_LIMIT_A = "service_import_limit_a"
CONF_EXPORT_LIMIT_KW = "export_limit_kw"
CONF_INVERTER_CHARGE_LIMIT_KW = "inverter_charge_limit_kw"
CONF_INVERTER_DISCHARGE_LIMIT_KW = "inverter_discharge_limit_kw"
CONF_HOUSE_LOAD = "house_load_entity"
CONF_HEATER_POWER = "heater_power_entity"
CONF_SOLAR_POWER = "solar_power_entity"
CONF_SOLAR_POWER_DIRECTION = "solar_power_generation_direction"
CONF_RESERVE = "reserve_kwh"
CONF_EV_SOC = "ev_soc_entity"
CONF_EV_MAX_CURRENT = "ev_max_current"
CONF_EV_MIN_CURRENT = "ev_min_current"
CONF_EV_VOLTAGE = "ev_voltage"
CONF_EV_PHASE_COUNT = "ev_phase_count"
CONF_BONUS_WINDOW_START = "bonus_window_start"
CONF_BONUS_WINDOW_END = "bonus_window_end"
CONF_ZERO_IMPORT_THRESHOLD_KW = "zero_import_threshold_kw"
CONF_ZERO_IMPORT_CONFIRM_MINUTES = "zero_import_confirm_minutes"
CONF_FREE_CHARGE_START = "free_charge_window_start"
CONF_FREE_CHARGE_END = "free_charge_window_end"
CONF_HOUSE_LEARNING_FALLBACK = "house_learning_fallback_kwh"
CONF_HOUSE_AWAY_FALLBACK = "house_away_fallback_kwh"
CONF_HOUSE_AWAY_CONFIRMATION_HOURS = "house_away_confirmation_hours"
CONF_HOUSE_OCCUPANCY_MODE = "house_occupancy_mode"
CONF_AUTOMATIC_CONTROL_ENABLED = "automatic_control_enabled"
CONF_AUTOMATIC_EXPORT_ENABLED = "automatic_export_enabled"
CONF_EV_AUTOMATIC_CONTROL_ENABLED = "ev_automatic_control_enabled"
CONF_EXPORT_ALLOWANCE_KWH = "export_allowance_kwh"
CONF_EXPORT_DISCHARGE_POWER_KW = "export_discharge_power_kw"
CONF_DISCHARGE_EFFICIENCY_PERCENT = "discharge_efficiency_percent"
CONF_FORCE_DISCHARGE_FINISH = "force_discharge_finish"
CONF_EV_PROTECTED_BASELINE_A = "ev_protected_baseline_a"
CONF_FOXESS_CONTROL_OWNER = "foxess_control_owner"
CONF_REHEARSAL_MODE = "rehearsal_mode"

# Explicit, short-lived commissioning tests. These are independent of the
# automatic scheduler and remain unavailable until the control gate is opened.
SERVICE_TEST_FORCE_CHARGE = "test_force_charge"
SERVICE_TEST_FORCE_DISCHARGE = "test_force_discharge"
SERVICE_TEST_STOP = "test_stop"

# Actuator mappings are collected for commissioning and diagnostics. The
# observer release never writes to these entities; an active release must
# still pass every mapping through its explicit safety gate.
CONF_FOXESS_WORK_MODE = "foxess_work_mode_entity"
CONF_FOXESS_FORCE_CHARGE_POWER = "foxess_force_charge_power_entity"
CONF_FOXESS_FORCE_DISCHARGE_POWER = "foxess_force_discharge_power_entity"
CONF_EV_AT_HOME = "ev_at_home_entity"
CONF_EV_CABLE_CONNECTED = "ev_cable_connected_entity"
CONF_EV_CHARGING_STATE = "ev_charging_state_entity"
CONF_EV_ACTUAL_CURRENT = "ev_actual_current_entity"
CONF_EV_STORED_ENERGY = "ev_stored_energy_entity"
CONF_EV_LIFETIME_ENERGY = "ev_lifetime_energy_entity"
CONF_EV_CURRENT_LIMIT = "ev_current_limit_entity"
CONF_EV_CHARGE_LIMIT = "ev_charge_limit_entity"
CONF_EV_CHARGE_SWITCH = "ev_charge_switch_entity"
CONF_EV_CHARGE_PATH = "ev_charge_path"
CONF_EV_SMART_SOCKET = "ev_smart_socket_entity"
CONF_EV_SMART_SOCKET_CURRENT_LIMIT = "ev_smart_socket_current_limit_a"
CONF_EV_SMART_SOCKET_SETTLE_SECONDS = "ev_smart_socket_settle_seconds"
CONF_EV_SMART_SOCKET_RETRY_SECONDS = "ev_smart_socket_retry_seconds"
CONF_EV_SMART_SOCKET_POWER_SWITCHING = "ev_smart_socket_power_switching"
CONF_EV_SMART_RECOVERY_NO_POWER_SECONDS = "ev_smart_recovery_no_power_seconds"
CONF_EV_SMART_RECOVERY_CURRENT_CONFIRM_SECONDS = (
    "ev_smart_recovery_current_confirm_seconds"
)
CONF_EV_SMART_RECOVERY_SOCKET_CONFIRM_SECONDS = (
    "ev_smart_recovery_socket_confirm_seconds"
)
CONF_EV_SMART_RECOVERY_POWER_OFF_SECONDS = "ev_smart_recovery_power_off_seconds"
CONF_EV_SMART_RECOVERY_POST_POWER_SECONDS = "ev_smart_recovery_post_power_seconds"
CONF_EV_SMART_RECOVERY_CHARGING_CONFIRM_SECONDS = (
    "ev_smart_recovery_charging_confirm_seconds"
)
CONF_EV_SMART_RECOVERY_REARM_SECONDS = "ev_smart_recovery_rearm_seconds"
CONF_EV_SMART_RECOVERY_IDLE_CURRENT_A = "ev_smart_recovery_idle_current_a"
# Legacy YAML-helper mapping retained only as a compatibility fallback.
CONF_EV_CHARGE_TO_FULL = "ev_charge_to_full_entity"
CONF_EV_CHARGE_TO_FULL_ENABLED = "ev_charge_to_full_enabled"
CONF_EV_LOCATION_MODE = "ev_location_mode"
CONF_EV_FREE_WINDOW_PRIORITY = "ev_free_window_priority"
CONF_EV_FREE_WINDOW_CHARGE_LIMIT = "ev_free_window_charge_limit_percent"
CONF_EV_FREE_WINDOW_MINIMUM_CURRENT = "ev_free_window_minimum_current_a"
CONF_EV_FREE_WINDOW_SETTLE_MINUTES = "ev_free_window_settle_minutes"
CONF_EV_DIRECT_LIMIT_HEADROOM = "ev_direct_limit_headroom_percent"
CONF_EV_CHARGE_EFFICIENCY = "ev_charge_efficiency_percent"
CONF_EV_ARRIVAL_RESERVE_SOC = "ev_arrival_reserve_soc_percent"
CONF_EV_LEARNING_MINIMUM_SAMPLES = "ev_learning_minimum_samples"
CONF_SITE_GRID_HEADROOM_CURRENT = "site_grid_headroom_current_a"
CONF_SITE_GRID_CURRENT = "site_grid_current_entity"
CONF_SITE_GRID_CURRENT_DIRECTION = "site_grid_current_positive_direction"
CONF_SIGN_CONVENTIONS_VERIFIED = "sign_conventions_verified"
CONF_TELEMETRY_MAX_AGE_SECONDS = "telemetry_max_age_seconds"
CONF_BATTERY_FREE_WINDOW_TARGET = "battery_free_window_target_percent"
CONF_BATTERY_CHARGE_EFFICIENCY = "battery_charge_efficiency_percent"
CONF_EV_ALLOWANCE_GUARD_ENABLED = "ev_allowance_guard_enabled"
CONF_EV_ALLOWANCE_SAFETY_MARGIN = "ev_allowance_safety_margin_kwh"
CONF_EV_SOLAR_SPILL_ENABLED = "ev_solar_spill_enabled"
CONF_EV_SOLAR_SPILL_BATTERY_SOC = "ev_solar_spill_battery_soc_percent"
CONF_EV_PRE_FREE_ENABLED = "ev_pre_free_backfill_enabled"
CONF_EV_TELEMETRY_MAX_AGE_SECONDS = "ev_telemetry_max_age_seconds"
CONF_EV_TELEMETRY_MAX_SKEW_SECONDS = "ev_telemetry_max_skew_seconds"
CONF_EV_CONTROL_COMMISSIONED = "ev_control_commissioned"
EV_REQUIRED_ENTITY_KEYS = (
    CONF_EV_SOC,
    CONF_EV_AT_HOME,
    CONF_EV_CABLE_CONNECTED,
    CONF_EV_CHARGING_STATE,
    CONF_EV_ACTUAL_CURRENT,
    CONF_EV_STORED_ENERGY,
    CONF_EV_CURRENT_LIMIT,
    CONF_EV_CHARGE_LIMIT,
    CONF_EV_CHARGE_SWITCH,
)

DEFAULT_BATTERY_FLOOR = 10.0
DEFAULT_RESERVE_KWH = 0.0
DEFAULT_DAILY_FREE_ALLOWANCE_KWH = 50.0
DEFAULT_PEAK_WINDOW_START = "16:00:00"
DEFAULT_PEAK_WINDOW_END = "23:00:00"
DEFAULT_PEAK_RATE = 0.594
DEFAULT_OFFPEAK_RATE = 0.0
DEFAULT_OFFPEAK_BALANCE_RATE = 0.308
DEFAULT_SHOULDER_RATE = 0.528
DEFAULT_EXPORT_RATE = 0.0
DEFAULT_SUPER_EXPORT_RATE = 0.10
DEFAULT_DAILY_CHARGE = 2.035
DEFAULT_ZERO_IMPORT_THRESHOLD_KW = 0.03
DEFAULT_ZERO_IMPORT_CONFIRM_MINUTES = 5.0
DEFAULT_SITE_PHASE_COUNT = 1
DEFAULT_SERVICE_IMPORT_LIMIT_A = 0.0
DEFAULT_EXPORT_LIMIT_KW = 0.0
DEFAULT_INVERTER_CHARGE_LIMIT_KW = 0.0
DEFAULT_INVERTER_DISCHARGE_LIMIT_KW = 0.0
DEFAULT_EV_VOLTAGE = 230.0
DEFAULT_EV_PHASE_COUNT = 1
DEFAULT_EV_MIN_CURRENT = 0.0
DEFAULT_EV_MAX_CURRENT = 0.0
DEFAULT_FREE_CHARGE_START = "12:01:00"
DEFAULT_FREE_CHARGE_END = "14:59:00"
DEFAULT_HOUSE_LEARNING_FALLBACK_KWH = 17.5
DEFAULT_HOUSE_AWAY_FALLBACK_KWH = 6.5
DEFAULT_HOUSE_AWAY_CONFIRMATION_HOURS = 6.0
DEFAULT_HOUSE_OCCUPANCY_MODE = "auto"
HOUSE_OCCUPANCY_MODES = ("auto", "home", "away")
DEFAULT_AUTOMATIC_CONTROL_ENABLED = False
DEFAULT_AUTOMATIC_EXPORT_ENABLED = False
DEFAULT_EV_AUTOMATIC_CONTROL_ENABLED = False
DEFAULT_EXPORT_ALLOWANCE_KWH = 15.0
DEFAULT_EXPORT_DISCHARGE_POWER_KW = 10.0
DEFAULT_DISCHARGE_EFFICIENCY_PERCENT = 95.0
DEFAULT_FORCE_DISCHARGE_FINISH = "21:01:00"
DEFAULT_EV_PROTECTED_BASELINE_A = 0.0
DEFAULT_EV_LOCATION_MODE = "auto"
EV_LOCATION_MODES = ("auto", "home", "away")
DEFAULT_EV_FREE_WINDOW_PRIORITY = "ev"
EV_FREE_WINDOW_PRIORITIES = ("house_battery", "ev")
DEFAULT_EV_FREE_WINDOW_CHARGE_LIMIT = 90.0
DEFAULT_EV_FREE_WINDOW_MINIMUM_CURRENT = 1.0
DEFAULT_EV_FREE_WINDOW_SETTLE_MINUTES = 5.0
DEFAULT_EV_DIRECT_LIMIT_HEADROOM = 2.0
DEFAULT_EV_CHARGE_EFFICIENCY = 90.0
DEFAULT_EV_ARRIVAL_RESERVE_SOC = 20.0
DEFAULT_EV_LEARNING_MINIMUM_SAMPLES = 14
DEFAULT_SITE_GRID_HEADROOM_CURRENT = 1.0
DEFAULT_BATTERY_FREE_WINDOW_TARGET = 100.0
DEFAULT_BATTERY_CHARGE_EFFICIENCY = 95.0
DEFAULT_BATTERY_CHARGE_POSITIVE = True
GRID_POSITIVE_IMPORT = "positive_import"
GRID_POSITIVE_EXPORT = "positive_export"
GRID_POWER_DIRECTIONS = (GRID_POSITIVE_IMPORT, GRID_POSITIVE_EXPORT)
BATTERY_POSITIVE_CHARGE = "positive_charge"
BATTERY_POSITIVE_DISCHARGE = "positive_discharge"
BATTERY_POWER_DIRECTIONS = (BATTERY_POSITIVE_CHARGE, BATTERY_POSITIVE_DISCHARGE)
SOLAR_GENERATION_POSITIVE = "generation_positive"
SOLAR_GENERATION_NEGATIVE = "generation_negative"
SOLAR_POWER_DIRECTIONS = (SOLAR_GENERATION_POSITIVE, SOLAR_GENERATION_NEGATIVE)
DEFAULT_GRID_POWER_DIRECTION = GRID_POSITIVE_IMPORT
DEFAULT_BATTERY_POWER_DIRECTION = BATTERY_POSITIVE_CHARGE
DEFAULT_SOLAR_POWER_DIRECTION = SOLAR_GENERATION_POSITIVE
DEFAULT_SITE_GRID_CURRENT_DIRECTION = GRID_POSITIVE_IMPORT
DEFAULT_SIGN_CONVENTIONS_VERIFIED = False
DEFAULT_TELEMETRY_MAX_AGE_SECONDS = 90.0
DEFAULT_EV_ALLOWANCE_GUARD_ENABLED = True
DEFAULT_EV_ALLOWANCE_SAFETY_MARGIN = 0.0
DEFAULT_EV_SOLAR_SPILL_ENABLED = False
DEFAULT_EV_SOLAR_SPILL_BATTERY_SOC = 100.0
DEFAULT_EV_PRE_FREE_ENABLED = False
DEFAULT_EV_TELEMETRY_MAX_AGE_SECONDS = 90.0
DEFAULT_EV_TELEMETRY_MAX_SKEW_SECONDS = 30.0
DEFAULT_EV_CONTROL_COMMISSIONED = False
DEFAULT_EV_CHARGE_TO_FULL_ENABLED = False
EV_CHARGE_PATH_DIRECT = "direct_evse"
EV_CHARGE_PATH_SMART_SOCKET = "smart_socket"
EV_CHARGE_PATHS = (EV_CHARGE_PATH_DIRECT, EV_CHARGE_PATH_SMART_SOCKET)
DEFAULT_EV_CHARGE_PATH = EV_CHARGE_PATH_DIRECT
DEFAULT_EV_SMART_SOCKET_CURRENT_LIMIT = 0.0
DEFAULT_EV_SMART_SOCKET_SETTLE_SECONDS = 15.0
DEFAULT_EV_SMART_SOCKET_RETRY_SECONDS = 300.0
DEFAULT_EV_SMART_SOCKET_POWER_SWITCHING = False
DEFAULT_EV_SMART_RECOVERY_NO_POWER_SECONDS = 120.0
DEFAULT_EV_SMART_RECOVERY_CURRENT_CONFIRM_SECONDS = 60.0
DEFAULT_EV_SMART_RECOVERY_SOCKET_CONFIRM_SECONDS = 15.0
DEFAULT_EV_SMART_RECOVERY_POWER_OFF_SECONDS = 30.0
DEFAULT_EV_SMART_RECOVERY_POST_POWER_SECONDS = 20.0
DEFAULT_EV_SMART_RECOVERY_CHARGING_CONFIRM_SECONDS = 180.0
DEFAULT_EV_SMART_RECOVERY_REARM_SECONDS = 120.0
DEFAULT_EV_SMART_RECOVERY_IDLE_CURRENT_A = 0.5
FOXESS_CONTROL_OWNER_OBSERVER = "observer_only"
FOXESS_CONTROL_OWNER_MODBUS = "local_modbus"
FOXESS_CONTROL_OWNER_CLOUD = "foxcloud_scheduler"
FOXESS_CONTROL_OWNERS = (
    FOXESS_CONTROL_OWNER_OBSERVER,
    FOXESS_CONTROL_OWNER_MODBUS,
    FOXESS_CONTROL_OWNER_CLOUD,
)
DEFAULT_FOXESS_CONTROL_OWNER = FOXESS_CONTROL_OWNER_OBSERVER
DEFAULT_REHEARSAL_MODE = True
DEFAULT_BONUS_WINDOW_START = "18:00:00"
DEFAULT_BONUS_WINDOW_END = "21:00:00"

REASON_INVALID_CONFIGURATION = "invalid_configuration"
REASON_MISSING_BATTERY_SOC = "missing_battery_soc"
REASON_MISSING_GRID_POWER = "missing_grid_power"
REASON_OBSERVER_ONLY = "observer_only"
