"""Generate the immutable configuration FieldSpec catalogue."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
CONTRACT_PATH = (
    REPOSITORY_ROOT
    / "docs"
    / "maintainability"
    / "config-field-contract-v0.12.26.json"
)
CATALOGUE_PATH = (
    REPOSITORY_ROOT
    / "custom_components"
    / "home_energy_orchestrator"
    / "field_catalogue.py"
)

_EV_PAGES = {"car", "charger", "ev_policies", "recovery"}


def _value_type(input_kind: str) -> str:
    return {
        "boolean": "bool",
        "entity": "entity_id",
        "number": "float",
        "select": "str",
        "text": "str",
        "time": "time",
    }[input_kind]


def _applicability(page: str) -> str:
    if page == "solar":
        return "solar"
    if page in _EV_PAGES:
        return "ev"
    return "always"


def _redaction(key: str, input_kind: str) -> str:
    if key == "name":
        return "redact"
    if input_kind == "entity":
        return "omit"
    return "retain"


def _field_line(field: dict[str, Any]) -> str:
    selector_config = field["input_config"]
    selector_config_json = (
        None
        if selector_config is None
        else json.dumps(selector_config, sort_keys=True, separators=(",", ":"))
    )
    return (
        "    FieldSpec("
        f"key={field['key']!r}, "
        f"value_type={_value_type(field['input_kind'])!r}, "
        f"default={field['default']!r}, "
        f"has_default={field['has_default']!r}, "
        f"selector_kind={field['input_kind']!r}, "
        f"selector_config_json={selector_config_json!r}, "
        f"page={field['page']!r}, "
        f"order={field['order']!r}, "
        f"required={field['required']!r}, "
        f"applicability={_applicability(field['page'])!r}, "
        f"redaction={_redaction(field['key'], field['input_kind'])!r}, "
        f"translation_key={field['key']!r}),"
    )


def rendered_catalogue() -> str:
    """Return deterministic Python source for every frozen wizard field."""
    contract = json.loads(CONTRACT_PATH.read_text(encoding="utf-8"))
    lines = [
        "# ruff: noqa: E501\n",
        '"""Generated immutable configuration field catalogue.\n',
        "\n",
        "Generated by ``scripts/field_catalogue.py`` from the reviewed v0.12.26\n",
        "configuration-field contract. Do not edit by hand.\n",
        '"""\n',
        "\n",
        "from __future__ import annotations\n",
        "\n",
        "from dataclasses import dataclass\n",
        "from types import MappingProxyType\n",
        "from typing import Literal\n",
        "\n",
        "\n",
        "@dataclass(frozen=True, slots=True)\n",
        "class FieldSpec:\n",
        '    """One stable persisted configuration-field definition."""\n',
        "\n",
        "    key: str\n",
        '    value_type: Literal["bool", "entity_id", "float", "str", "time"]\n',
        "    default: object\n",
        "    has_default: bool\n",
        "    selector_kind: str\n",
        "    selector_config_json: str | None\n",
        "    page: str\n",
        "    order: int\n",
        "    required: bool\n",
        '    applicability: Literal["always", "solar", "ev"]\n',
        '    redaction: Literal["retain", "redact", "omit"]\n',
        "    translation_key: str\n",
        "\n",
        "\n",
        'CATALOGUE_BASELINE = "0.12.26"\n',
        "FIELD_SPECS: tuple[FieldSpec, ...] = (\n",
    ]
    lines.extend(f"{_field_line(field)}\n" for field in contract["fields"])
    lines.extend(
        [
            ")\n",
            "FIELD_SPECS_BY_KEY = MappingProxyType(\n",
            "    {spec.key: spec for spec in FIELD_SPECS}\n",
            ")\n",
        ]
    )
    return "".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = rendered_catalogue()
    if args.write:
        CATALOGUE_PATH.write_text(rendered, encoding="utf-8")
    if args.check and (
        not CATALOGUE_PATH.is_file()
        or CATALOGUE_PATH.read_text(encoding="utf-8") != rendered
    ):
        raise SystemExit("FieldSpec catalogue changed; review and regenerate")
    if not args.write and not args.check:
        print(rendered, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
